language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.0.0

before_script:
  - chmod +x gradlew
    - chmod +x ./ci/wait_for_emulator
    - ./ci/wait_for_emulator
    - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest